### ISSUE TITLE
score list

### ISSUE THREAD

**Issue by beli3ver** [scoute-dich/Sieben#1]
Wonderful APP.
Thanks for it love all your Apps.
Maybe you could add a score list with a overview how much exercises and minutes I train everday?
Maybe also a setting, to select a type of body I want to train, legs, arms something like that.

**Comment by scoute-dich** [comment]
Hi,

@beli3ver that's areal good idea. I want this feature also, but I think that's above my abilities. I'm not a real developer. All I know I learned from google and same tutorials. I just made this app because I want to use as much open source apps as possible, and there are no functional open source apps out there whether on playstore nor on f-droid nor on github...

If you want such features you need to install a proprietary app from playstore. Perhaps in future (on day far away) if have the time for learning how to implement database management and advanced settings management...

Until then... best wishes...
scoute-dich

P.S.: I'm glad that you enjoy my apps.

**Comment by beli3ver** [comment]
Hi @scoute-dich ,

database in Android it really simple:

http://developer.android.com/training/basics/data-storage/databases.html

Maybe I could help you, I didn't like Google so I only use F-Droid Apps.

**Comment by cipo7741** [comment]
Thanks for this great App. Your a better developer than any of the dark-pattern implementers out there.
Just wanted to add: I liked the minimal approach.
No settings, no statistics, no remainder. Just wanna do some ecercise.

**Comment by scoute-dich** [comment]
Good news: statistics (only a few) will be introduced in the next version. ;-)

**Comment by scoute-dich** [comment]
Will be in next update.
