### ISSUE TITLE
Easier workout

### ISSUE THREAD

**Issue by achimwagenknecht** [scoute-dich/Sieben#20]
The app is really great! Would it be possible to generate an easier version of the workout, e.g. for older or completely untrained people? Maybe just replace the pictures with easier variants. (Wall sit with higher rest, push ups with hands on chair or table, stair in place of chair, etc.)

**Comment by scoute-dich** [comment]
Hi, because of my spare time, I will not be able to make this possible. The seven minute workout is for people which have already a "kind of fitness" and are trained. So I am sorry.

I leave the issue open (for a time), if somebody is also interested in such an enhancement, he can fork the project and implement this.

I hope you can understand this.

**Comment by achimwagenknecht** [comment]
No problem. I can understand this.
