### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/Sieben#26]
When i perform these sequences of events, the dialog on screen disappears

1. Click on ... to open action overflow menu
2. Click on Settings
3. Click on 
a. Duration
b. Help
c. License
4. Orientation Change

**Comment by scoute-dich** [comment]
Since you know, that is the default behavior of android. When changing orientation the view gets recreated. Since that is not a problem for me or other users I won't do anything concerning this issue. And yes I know that you are "exploring mobile GUI failures for research purposes". I wish you luck with your project.
